image: "python:3.7"
before_script:
   - pip install -r requirements.txt

stages:
  - build
  - static analysis
  - test

#migrations:
 # stage: build
  #script:
   # - python3 manage.py makemigrations
    #- python3 manage.py makemigrations roottoplate
    #- python3 manage.py migrate
    #- python3 manage.py check

flake8:
  stage: static analysis
  script:
    - flake8 --max-line-length=120 roottoplate/*.py

django-tests:
  stage: test
  script:
    - python3 manage.py test
