default:
  tags:
    - shell

# this executes before each job, and sets up the requirements
before_script:
    # pip is not in a discoverable folder so add the folder it's in to the list of executable folders :/
    - export PATH="/home/gitlab-runner/.local/bin:$PATH"
    - pip install django
    - python3 -m pip install -r requirements.txt

stages:
  - static analysis
  - test

test-job1:
  stage: test
  script:
    - python3 manage.py test

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "no that's stupid"
