variables:
  DJANGO_CONFIG: "test"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
default:
  image: python
  tags:
    - docker

  cache:
    paths:
      - .cache/pip/
      - venv/

  before_script:
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt

stages:
  - build
  - test
  - deploy

#django-tests:
#  stage: test
#  script:
#    - cd roottoplate
#    - python3 manage.py test

static-analysis:
  stage: test
  script:
    - python -m pip install flake8
    - flake8 --extend-exclude=venv/
    - flake8 .

heroku_deploy:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install -y ruby ruby-dev rubygems-integration
    - gem install dpl
    - dpl --provider=heroku --app=roottoplate --api-key=73562996-0279-4eba-8859-3c9b0460e28a
