# Generated by Django 4.1.7 on 2023-03-09 10:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('entryID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('gas', models.IntegerField()),
                ('electricity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('woodChipRatio', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('CNRatio', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRequest',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=1024)),
                ('dateRequested', models.DateTimeField()),
                ('deadlineDate', models.DateTimeField()),
                ('email', models.CharField(max_length=128)),
                ('phoneNumber', models.IntegerField(null=True)),
                ('notes', models.CharField(blank=True, max_length=20048, null=True)),
                ('numberOfBags', models.IntegerField(null=True)),
                ('collected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureEntry',
            fields=[
                ('entryID', models.AutoField(primary_key=True, serialize=False)),
                ('entryTime', models.DateTimeField()),
                ('probe1', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(-40), django.core.validators.MaxValueValidator(150)])),
                ('probe2', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(-40), django.core.validators.MaxValueValidator(150)])),
                ('probe3', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(-40), django.core.validators.MaxValueValidator(150)])),
                ('probe4', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(-40), django.core.validators.MaxValueValidator(150)])),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Temperature entries',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('outputID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InputEntry',
            fields=[
                ('entryID', models.AutoField(primary_key=True, serialize=False)),
                ('entryTime', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Input entries',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputAmount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('inputEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composter.inputentry')),
                ('inputType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composter.inputtype')),
            ],
        ),
    ]
