# Generated by Django 4.1.3 on 2023-02-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyUsage",
            fields=[
                ("entryID", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("gas", models.IntegerField()),
                ("electricity", models.IntegerField()),
            ],
        ),
    ]
