# Generated by Django 4.1.3 on 2023-03-01 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composter', '0002_energyusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputtype',
            name='woodChipRatio',
        ),
        migrations.AddField(
            model_name='inputtype',
            name='moisturePercent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputtype',
            name='nitrogenPercent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
